// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://wcrdnljoxscotvuxsczd.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6IndjcmRubGpveHNjb3R2dXhzY3pkIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTU3MTIxMTEsImV4cCI6MjA3MTI4ODExMX0.GGZ6lifIsh8YFQ77YD6woxjkYcE4nxSlskxR-Q1SH3c";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});